- class-detail-components/DynamicButtonSection/index.jsx
- class-detail-components/FitnessClassDetailsSection/index.jsx
Removed Booking Schedule Button and Added GroupPrice to class heading
> Removed Booking Schedule Button and Added GroupPrice to class heading

- class-detail-components/BookingComponent/index.jsx
- class-detail-components/DynamicButtonSection/index.jsx
- class-detail-components/FitnessClassDetailsSection/index.jsx
- home-components/MusicianProfileCard1/index.jsx
- Added a Booking Button that scroll downs to Booking Schedule
- Fixed Icons on class and home page
> Added Booking Button back again and Fixed Category Icon

- class-detail-components/BookingComponent/index.jsx
- class-detail-components/FitnessClassDetailsSection/index.jsx
- package-lock.json
- package.json
- pages/api/generateMeetLink.js
- pages/createClass.js
- pages/schedule.js
- pages/updateClass/[id].js
- yarn.lock
- Added Google Meet functionality
> Added google meet functionality for online classes

- class-detail-components/BookingComponent/index.jsx
- class-detail-components/FitnessClassDetailsSection/index.jsx
- package-lock.json
- package.json
- pages/createClass.js
- pages/updateClass/[id].js
- yarn.lock
Invite Fixes and Minor UI Changes
> Online class Fixes

- class-detail-components/BookingComponent/index.jsx
- class-detail-components/FitnessClassDetailsSection/index.jsx
Fixed Issue where it was comparing User timezone with instructor timezone and causing slot display errors in case of mismatch
> Fixed Timezone mismatch in Bookings Page

- pages/updateClass/[id].js
Fixed Delete Image and Added restriction to Image Input
> Fixed Delete Image and Added restriction to Image Input

- pages/api/isPayoutsEnabled.js
- pages/api/updateOnboardingLinks.js
Fixed Infinite loading on StripeAdded
> Fixed Infinite loading on StripeAdded

- components/NewHeader.js
- pages/addStripe.js
- pages/api/createExternalAccount.js
- pages/stripeAdded.js
- pages/stripeRefresh.js
> Fixed Stripe Integration

- class-detail-components/BookingComponent/index.jsx
- components/InstructorClasses/index.js
- pages/schedule.js
Added Feature to add Multiple students in group classes
> Added Feature to add Multiple students in group classes

- class-detail-components/BookingComponent/index.jsx
- class-detail-components/PostReviewSection/index.jsx
- class-detail-components/ReviewCard/index.jsx
- pages/api/sendReviewMail.js
- pages/classes/[id].js
- vercel.json
> Review Emails and Fixes

- class-detail-components/FAQAccordion.js
- class-detail-components/FitnessClassDetailsSection/index.jsx
- class-detail-components/ReviewCard/index.jsx
- pages/updateProfile/[id].js
> Features Accordian

- home-components/MusicianProfileCard1/index.jsx
- pages/createClass.js
- pages/updateClass/[id].js
Fix: Class Card and Create class(Package)
> Fix: Class Card and Create class(Package)

- class-detail-components/FAQAccordion.js
- components/RescheduleClass/index.jsx
- components/StudentClasses/StudentCard.js
- components/StudentClasses/index.js
- pages/api/sendReminderMail.js
- pages/myClass/[id].js
Added new Feature: Reschedule Classes
> Feature: Reschedule Classes

- class-detail-components/BookingComponent/index.jsx
- class-detail-components/MindfulClassCard/index.jsx
- class-detail-components/MindfulClassDisplay/index.jsx
- components/StudentClasses/StudentCard.js
- components/StudentClasses/index.js
- pages/api/instructor-refund.js
- pages/api/refund.js
- pages/api/transferPayments.js
Feature: Buy Packages and book classes using package credit
> Feature: Buy Packages and book classes using package credit

- class-detail-components/MindfulClassCard/index.jsx
- components/CancellationPackagePolicy.js
- components/ConfirmPackageDetails.js
- components/NewHeader.js
- components/StudentPackageCard.js
- pages/confirmPackage/[id].js
- pages/myPackages.js
- vercel.json
Feature: My Packages
Also added Confirmation Page after package purchase
> Feature: My Packages

- pages/browse/[category]/[subCategory].js
- pages/browse/index.js
Added current location marker
Minor fixes to map
Changed classes card
> Added current location marker

- pages/browse/[category]/[subCategory].js
- pages/browse/index.js
Fix: Zoom to include all markers on map
Also added border to classes on browse page
> Fix: Zoom to include all markers on map

- pages/browse/[category]/[subCategory].js
- pages/browse/index.js
Removed Zooming to class marker on hover
> Removed Zooming to class marker on hover

- pages/browse/[category]/[subCategory].js
Added meta data for dynamic pages
> Added meta data for dynamic pages

- class-detail-components/BookingComponent/index.jsx
- class-detail-components/FitnessClassDetailsSection/index.jsx
- class-detail-components/PricingSection/index.jsx
Added package options in Book Now section
> Added package options in Book Now section

- home-components/DynamicContentLayout/index.jsx
- pages/browse/[category]/[subCategory].js
- pages/browse/[category]/index.js
In this i just added Link to the browse page, though i have other solution also in which i have added an index file so every url structure like browse/sport can also be handled and this is the one which i did not pushed.
> Dev Aryan Assasment- Redirecting Find Classes

- class-detail-components/FineArtDegreeSection/index.jsx
- class-detail-components/FitnessBioSection/index.jsx
- class-detail-components/FitnessDescriptionSection/index.jsx
- class-detail-components/PricingSection/index.jsx
- styles/globals.css
- tailwind.config.js
The read more will only be visible if the text is to be covered in bigger than 150(pre-defined criteria in the code) and the full word is shown at the last when the read more appears followed by '...' in the button section please refer to the video - 
https://github.com/user-attachments/assets/85f5185f-b9ab-4288-b426-a5373365fba3
Initially(that is when page load for the first time) none of the button would be selected
> Redesigning price button and read more

- class-detail-components/DynamicButtonSection/index.jsx
- class-detail-components/FitnessClassDetailsSection/index.jsx
- class-detail-components/FitnessReviewSectionWidget/index.jsx
- class-detail-components/PricingSection/index.jsx
- components/ClassLocationMap.js
- Revamped Mobile UI
- Fixed Desktop UI inconsistencies
> Fix classes page
